MAPS = {
    "cm_archives": {
        "en": "Archivum Sycorax",
        "zh-tw": "塞科拉克斯檔案館",
        "zh-cn": "塞科拉克斯档案馆",
        "image": "Archivum_Sycorax.png",
    },
    "dm_rise": {
        "en": "Ascension Riser 31",
        "zh-tw": "31號升降機",
        "zh-cn": "31号升降机",
        "image": "Ascension_Riser_31.png",
    },
    "lm_rails": {
        "en": "Chasm Logistratum",
        "zh-tw": "隘口後勤處",
        "zh-cn": "隘口后勤处",
        "image": "Chasm_Logistratum.png",
    },
    "km_station": {
        "en": "Chasm Station HL-16-11",
        "zh-tw": "HL-16-11 隘口站",
        "zh-cn": "HL-16-11 隘口站",
        "image": "Chasm_Station_HL-16-11.png",
    },
    "core_research": {
        "en": "Clandestium Gloriana",
        "zh-tw": "克蘭岱斯提恩 - 格洛里亞納",
        "zh-cn": "荣光女王秘所",
        "image": "Clandestium_Gloriana.png",
    },
    "hm_complex": {
        "en": "Comms-Plex 154/2f",
        "zh-tw": "154/2f 通訊站",
        "zh-cn": "154/2f 通讯站",
        "image": "Comms-Plex_1542f.png",
    },
    "fm_cargo": {
        "en": "Consignment Yard HL-17-36",
        "zh-tw": "HL-17-36 托運場",
        "zh-cn": "HL-17-36 货运站",
        "image": "Consignment_Yard_HL-17-36.png",
    },
    "km_heresy": {
        "en": "Dark Communion",
        "zh-tw": "黑暗傳教團",
        "zh-cn": "黑暗传教团",
        "image": "Dark_Communion.png",
    },
    "fm_resurgence": {
        "en": "Enclavum Baross",
        "zh-tw": "巴羅斯飛地",
        "zh-cn": "巴洛斯飞地",
        "image": "Enclavum_Baross.png",
    },
    "lm_scavenge": {
        "en": "Excise Vault Spireside-13",
        "zh-tw": "尖塔區 - 13贓物庫",
        "zh-cn": "尖塔区 - 13赃物库",
        "image": "Excise_Vault_Spireside-13.png",
    },
    "cm_habs": {
        "en": "Hab Dreyko",
        "zh-tw": "德雷科居住區",
        "zh-cn": "德雷克居住区",
        "image": "Hab_Dreyko.png",
    },
    "km_enforcer": {
        "en": "Magistrati Oubliette TM8-707",
        "zh-tw": "TM8-708 法庭密牢",
        "zh-cn": "TM8-708 法庭密牢",
        "image": "Magistrati_Oubliette_TM8-707.png",
    },
    "fm_armoury": {
        "en": "Mercantile HL-70-04",
        "zh-tw": "HL-70-04 貿易區",
        "zh-cn": "HL-70-04 贸易区",
        "image": "Mercantile_HL-70-04.png",
    },
    "lm_cooling": {
        "en": "Power Matrix HL-17-36",
        "zh-tw": "HL-17-36 能量矩陣",
        "zh-cn": "HL-17-36 电力矩阵",
        "image": "Power_Matrix_HL-17-36.png",
    },
    "hm_strain": {
        "en": "Refinery Delta-17",
        "zh-tw": "D17 - 精煉廠",
        "zh-cn": "D17 - 精炼厂",
        "image": "Refinery_Delta-17.png",
    },
    "dm_propaganda": {
        "en": "Relay Station TRS-150",
        "zh-tw": "中繼站 TRS-150",
        "zh-cn": "中继站 TRS-150",
        "image": "Relay_Station_TRS-150.png",
    },
    "op_train": {
        "en": "Rolling Steel",
        "zh-tw": "末路特快車",
        "zh-cn": "钢轮滚滚",
        "image": "Rolling_Steel.png",
    },
    "dm_stockpile": {
        "en": "Silo Cluster 18-66/a",
        "zh-tw": "18-66/a 水倉群",
        "zh-cn": "18-66/a 水仓群",
        "image": "Silo_Cluster_18-66a.png",
    },
    "dm_forge": {
        "en": "Smelter Complex HL-17-36",
        "zh-tw": "HL-17-36 冶煉廠大樓",
        "zh-cn": "HL-17-36 冶炼厂大楼",
        "image": "Smelter_Complex_HL-17-36.png",
    },
    "km_enforcer_twins": {
        "en": "The Orthus Offensive",
        "zh-tw": "雙頭犬攻勢 (雙子)",
        "zh-cn": "奥都斯攻势 (双子)",
        "image": "The_Orthus_Offensive.png",
    },
    "hm_cartel": {
        "en": "Vigil Station Oblivium",
        "zh-tw": "奧布里維姆守夜站",
        "zh-cn": "奥布里维姆监测站",
        "image": "Vigil_Station_Oblivium.png",
    },
    "cm_raid": {
        "en": "Warren 6-19",
        "zh-tw": "窄巷區 6-19",
        "zh-cn": "窄道 6-19",
        "image": "Warren_6-19.png",
    },
}
